name: API CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
    steps:
      - name: üì¶ Checkout Repository
        uses: actions/checkout@v4

      - name: üîë Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: üê≥ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üöÄ Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/chart-pattern:api-latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: self-hosted
    timeout-minutes: 60
    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
    steps:
      - name: üì¶ Checkout Repository
        uses: actions/checkout@v4

      - name: üöÄ Deploy
        run: |
          echo "$(date): Ïª®ÌÖåÏù¥ÎÑà Ïù¥ÎØ∏ÏßÄ ÌíÄ"
          docker compose pull api
          
          echo "$(date): Ïª®ÌÖåÏù¥ÎÑà ÏãúÏûë"
          docker compose up -d api

      - name: ‚úÖ Health Check
        run: |
          echo "Verifying deployment..."
          docker compose ps api

          CONTAINER_ID=$(docker compose ps api --status running --quiet)

          if [ -n "$CONTAINER_ID" ]; then
            echo "‚úÖ API container is running successfully"
          else
            echo "‚ùå API container is not running"
            exit 1
          fi

          echo "üìã Recent api logs:"
          docker compose logs --tail=10 api